# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none #triggered by PR

pool:
  vmImage: windows-latest

stages:   
- stage: Test
  displayName: 'Deploy to Test APIM and Run Integration Tests'
  jobs:
    - deployment: 
      displayName: 'Deploy and Test'
      environment: 'apim-internal-test'
      variables:
        azSubId: 6f4fe300-6d89-4272-8aa9-223e28d46391
        rgName: rg-apiint-test-eastus
        location: East US
        stgAccountName: stgcmwapiinttesteastus
        stgContainerName: apimarmtemplates
        apimName: apim-internal-test-eastus
        DemoConfApiBaseUrl: https://apim-internal-test-eastus.azure-api.net/conference
        #DemoConfApiSubscriptionKey-Test: secret variable -- see UI
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureFileCopy@4
              displayName: Copy ARM Templates to Test Storage
              name: AzureFileCopy
              inputs:
                SourcePath: '$(Build.SourcesDirectory)/src/arm'
                azureSubscription: 'Chris Westbrook Internal Subscription'
                Destination: 'AzureBlob'
                storage: '$(stgAccountName)'
                ContainerName: '$(stgContainerName)'
                sasTokenTimeOutInMinutes: '60'

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Deploy Azure Templates in Test
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: Chris Westbrook Internal Subscription
                subscriptionId: $(azSubId)
                action: 'Create Or Update Resource Group'
                resourceGroupName: $(rgName)
                location: $(location)
                templateLocation: 'URL of the file'
                csmFileLink: '$(AzureFileCopy.StorageContainerUri)arm/cmwms.apim-internal.main.template.json$(AzureFileCopy.StorageContainerSasToken)'
                csmParametersFileLink: '$(AzureFileCopy.StorageContainerUri)arm/cmwms.apim-internal.main.template.parameters.json$(AzureFileCopy.StorageContainerSasToken)'
                overrideParameters: '-apimName $(apimName) -containerSasToken $(AzureFileCopy.StorageContainerSasToken) -PolicyXMLBaseUrl $(AzureFileCopy.StorageContainerUri)arm'
                deploymentMode: 'Incremental'

            - task: DotNetCoreCLI@2
              displayName: Run API Integration Tests
              inputs:
                command: 'test'
                projects: 'src/apim-internal.Tests/apim-internal.Tests.csproj'
              env:
                DemoConfApiSubscriptionKey: $(DemoConfApiSubscriptionKey-Test)
